project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Título"
        href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
