<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Régression multiple lineaire (6.1, 6.2)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.31/datatables.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./mutiple_linear_regression.html">Multiple Linear Regression</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./UQAC_Couleur.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlation &amp; Simple Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./non-parametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Other types of correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simple_linear_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mutiple_linear_regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Multiple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./oneway_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">One-way ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova_repeated_measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA with Repeated Measures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two-way-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Two-way ANOVA (fixed effects)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two_way_anova_fixed_random.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Two-way ANOVA (fixed and random effects)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two-way-anova-random-block.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Two-way ANOVA (random block)</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#data" id="toc-data" class="nav-link active" data-scroll-target="#data">Data</a></li>
  <li><a href="#distribution-of-c3" id="toc-distribution-of-c3" class="nav-link" data-scroll-target="#distribution-of-c3">Distribution of C3</a></li>
  <li><a href="#distribution-of-lc3-y-variable" id="toc-distribution-of-lc3-y-variable" class="nav-link" data-scroll-target="#distribution-of-lc3-y-variable">Distribution of LC3 (Y variable)</a></li>
  <li><a href="#correlation-matrix-plot-between-the-predictors" id="toc-correlation-matrix-plot-between-the-predictors" class="nav-link" data-scroll-target="#correlation-matrix-plot-between-the-predictors">Correlation matrix (plot) between the predictors</a></li>
  <li><a href="#correlation-matrix-between-the-predictors" id="toc-correlation-matrix-between-the-predictors" class="nav-link" data-scroll-target="#correlation-matrix-between-the-predictors">Correlation matrix between the predictors</a></li>
  <li><a href="#model-1-additive-model" id="toc-model-1-additive-model" class="nav-link" data-scroll-target="#model-1-additive-model">Model 1: additive model</a></li>
  <li><a href="#model-1-all-the-explanatory-variables" id="toc-model-1-all-the-explanatory-variables" class="nav-link" data-scroll-target="#model-1-all-the-explanatory-variables">Model 1: all the explanatory variables</a></li>
  <li><a href="#tolerance" id="toc-tolerance" class="nav-link" data-scroll-target="#tolerance">Tolerance</a></li>
  <li><a href="#model-2-with-interaction" id="toc-model-2-with-interaction" class="nav-link" data-scroll-target="#model-2-with-interaction">Model 2: with interaction</a></li>
  <li><a href="#model-3-centering-and-interaction" id="toc-model-3-centering-and-interaction" class="nav-link" data-scroll-target="#model-3-centering-and-interaction">Model 3: centering and interaction</a></li>
  <li><a href="#diagnostic-plots" id="toc-diagnostic-plots" class="nav-link" data-scroll-target="#diagnostic-plots">Diagnostic plots</a></li>
  <li><a href="#boxplot-of-residuals" id="toc-boxplot-of-residuals" class="nav-link" data-scroll-target="#boxplot-of-residuals">Boxplot of residuals</a></li>
  <li><a href="#model-4-stepwise-selection" id="toc-model-4-stepwise-selection" class="nav-link" data-scroll-target="#model-4-stepwise-selection">Model 4: stepwise selection</a></li>
  <li><a href="#backward-selection" id="toc-backward-selection" class="nav-link" data-scroll-target="#backward-selection">Backward selection</a></li>
  <li><a href="#metrics-aic-and-bic-for-variable-selection" id="toc-metrics-aic-and-bic-for-variable-selection" class="nav-link" data-scroll-target="#metrics-aic-and-bic-for-variable-selection">Metrics AIC and BIC for variable selection</a></li>
  <li><a href="#model-5-aic-for-selecting-the-best-model" id="toc-model-5-aic-for-selecting-the-best-model" class="nav-link" data-scroll-target="#model-5-aic-for-selecting-the-best-model">Model 5: AIC for selecting the best model</a></li>
  <li><a href="#when-to-use-aic-or-bic" id="toc-when-to-use-aic-or-bic" class="nav-link" data-scroll-target="#when-to-use-aic-or-bic">When to use AIC or BIC</a></li>
  <li><a href="#importance-of-rmse" id="toc-importance-of-rmse" class="nav-link" data-scroll-target="#importance-of-rmse">Importance of RMSE</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Régression multiple lineaire (6.1, 6.2)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>L’équation de régression multiple peut être écrite comme suit :</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1X_1 + \beta_2X_2 + \ldots + \beta_nX_n + \epsilon
\]</span></p>
<p>Où :</p>
<ul>
<li><span class="math inline">\(Y\)</span> est la variable dépendante (le résultat que vous prédisez),</li>
<li><span class="math inline">\(\beta_0\)</span> est l’interception (la valeur de <span class="math inline">\(Y\)</span> lorsque toutes les variables <span class="math inline">\(X\)</span> sont égales à 0),</li>
<li><span class="math inline">\(\beta_1, \beta_2, \ldots, \beta_n\)</span> sont les coefficients des variables indépendantes,</li>
<li><span class="math inline">\(X_1, X_2, \ldots, X_n\)</span> sont les variables indépendantes,</li>
<li><span class="math inline">\(\epsilon\)</span> est le terme d’erreur (la différence entre les valeurs réelles et prédites).</li>
</ul>
<p>We’ll be using the dataset <code>paruelo.csv (chap 6)</code>, boîte 6.1 p.&nbsp;112.</p>
<p><strong>Box 6.1 Worked example of multiple linear regression: relative abundance of plant functional types</strong></p>
<section id="data" class="level4">
<h4 class="anchored" data-anchor-id="data">Data</h4>
<p>Paruelo &amp; Lauenroth (1996) analyzed the geographic distribution and the effects of climate variables on the relative abundance of a number of plant functional types (PFTs) including shrubs, forbs, succulents (e.g.&nbsp;cacti), <span class="math inline">\(C_3\)</span> grasses and <span class="math inline">\(C_4\)</span> grasses. There were 73 sites across North America. The variables of interest are the relative abundance of <span class="math inline">\(C_3\)</span> plants, the latitude in centesimal degrees (LAT), the longitude in centesimal degrees (LONG), the mean annual precipitation in mm (MAP), the mean annual temperature in <span class="math inline">\(°C\)</span> (MAT), the proportion of MAP that fell in June, July and August (JJAMAP) and the proportion of MAP that fell in December, January and February (DJFMAP).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get thedata</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/paruelo.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>DT<span class="sc">::</span><span class="fu">datatable</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div class="datatables html-widget html-fill-item" id="htmlwidget-bc66c3106a91e1f6c964" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-bc66c3106a91e1f6c964">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73"],[0.65,0.65,0.76,0.75,0.33,0.03,0,0.02,0.05,0.05,0.36,0,0.21,0.51,0.07000000000000001,0.29,0.05,0.13,0,0.65,0,0.89,0.08,0.47,0,0,0.21,0.29,0.35,0.28,0.45,0.31,0.02,0.49,0.36,0.01,0,0,0.63,0.03,0.07000000000000001,0.12,0.36,0.63,0.86,0.47,0.58,0.68,0.71,0.06,0.04,0.14,0.06,0.34,0.31,0.21,0.6899999999999999,0.48,0.02,0.08,0.11,0.11,0.23,0.18,0.05,0.19,0.48,0.02,0,0,0.07000000000000001,0.31,0.72],[0,0,0.01,0.18,0.28,0.83,0.31,0.87,0.72,0.44,0.41,0.5,0.7,0.25,0.78,0.7,0,0,0.31,0.13,0.76,0,0.3,0.37,0,0.42,0.48,0,0.31,0.4,0,0,0.11,0,0,0.95,0.6,0.84,0,0,0,0,0,0.15,0.03,0.12,0.05,0.02,0.11,0.76,0.86,0.71,0.8,0,0,0,0,0,0,0.28,0.63,0,0.17,0.66,0.68,0.24,0.4,0.05,0.04,0,0.8,0.39,0.01],[199,469,536,476,484,623,259,969,542,421,446,376,661,575,885,556,344,415,347,575,477,370,537,870,356,570,457,327,176,345,405,375,231,723,365,373,733,351,244,244,207,646,593,409,409,409,409,495,717,935,976,1011,823,207,321,418,418,270,327,327,841,332,421,527,430,512,611,169,180,117,789,892,352],[12.4,7.5,7.2,8.199999999999999,4.8,12,14.5,15.3,13.9,8.5,5.1,11.2,17.8,6.1,12.9,8.6,6.6,6,18.9,5.3,13.9,3.5,16.7,15.4,7.3,12.2,8.800000000000001,9.5,13.8,6.4,5.9,5.7,12.1,11.2,6.9,11.5,9.4,11.7,7.2,7.2,7.2,10,11,7.5,7.5,7.5,7.5,7.9,7.5,20.7,21.2,17.7,19.5,7.2,6.5,5.9,5.9,6.9,9.5,9.5,20.1,7.8,3.9,7.4,9.5,2,4.2,17.1,15.1,18.1,12.9,6.6,2],[0.12,0.24,0.24,0.35,0.4,0.4,0.47,0.3,0.44,0.31,0.41,0.51,0.27,0.36,0.37,0.38,0.18,0.22,0.41,0.36,0.5,0.45,0.32,0.29,0.18,0.42,0.36,0.16,0.25,0.46,0.4,0.16,0.29,0.14,0.15,0.35,0.23,0.45,0.2,0.2,0.22,0.11,0.13,0.3,0.3,0.3,0.3,0.32,0.34,0.23,0.29,0.23,0.2,0.22,0.19,0.2,0.2,0.21,0.16,0.16,0.23,0.12,0.29,0.28,0.27,0.42,0.39,0.28,0.1,0.21,0.34,0.35,0.46],[0.45,0.29,0.2,0.15,0.14,0.11,0.17,0.14,0.13,0.14,0.15,0.17,0.16,0.16,0.12,0.12,0.35,0.33,0.12,0.13,0.22,0.19,0.12,0.15,0.31,0.24,0.13,0.31,0.28,0.14,0.12,0.29,0.21,0.34,0.31,0.18,0.37,0.18,0.29,0.29,0.28,0.36,0.35,0.2,0.2,0.2,0.2,0.17,0.15,0.22,0.18,0.19,0.21,0.28,0.35,0.38,0.38,0.27,0.31,0.31,0.22,0.4,0.18,0.16,0.16,0.12,0.16,0.32,0.49,0.39,0.13,0.15,0.14],[119.55,114.27,110.78,101.87,102.82,99.38,106.75,96.55,101.53,104.6,102.5,105.55,99.23,99.09999999999999,96.59999999999999,101.8,112.67,112.15,102.92,103.45,110.5,107.72,101.18,97.23,113.08,109.12,102.33,113.25,111.87,104.47,116.75,107.17,111.3,111.95,114.9,104.5,112.35,105.08,110.38,109.65,109.75,111.87,111.75,106.48,106.48,106.47,106.37,106,97,96.83,97,96,97.17,109.83,110.25,110.83,110.75,110,113.25,113.25,98.33,115.75,105.28,104.82,105.12,97.5,96.62,116.08,117.83,116.25,97.62,93.2,106.63],[46.4,47.32,45.78,43.95,46.9,38.87,32.62,36.95,35.3,40.82,47.75,33.48,33.33,45.33,39.1,41.55,43.73,44.25,29.58,43.53,31.6,50.7,32.97,36.05,41.87,32,43.75,38.17,37.1,45.03,39.82,41.42,38.52,40.17,39.16,38.55,35.27,34.28,40.47,40.45,39.88,39.92,40.12,45.82,45.87,45.88,45.85,45.48,43.5,30.58,29,33.75,31.33,39.66,40.08,40.5,40.58,40.5,38.5,38.5,30.25,40.33,41.12,41.25,42.07,49.87,47.75,36.83,36,36.67,38.75,45.4,52.13],[-0.1249387366083,-0.1249387366083,-0.0655015487564323,-0.0705810742857073,-0.366531544420413,-0.8860566476931629,-1,-0.920818753952375,-0.823908740944319,-0.823908740944319,-0.337242168318426,-1,-0.508638306165727,-0.214670164989233,-0.769551078621726,-0.408935392973501,-0.823908740944319,-0.638272163982407,-1,-0.1249387366083,-1,-0.00436480540245009,-0.744727494896694,-0.244125144327509,-1,-1,-0.508638306165727,-0.408935392973501,-0.346787486224656,-0.42021640338319,-0.259637310505756,-0.387216143280265,-0.920818753952375,-0.229147988357856,-0.337242168318426,-0.958607314841775,-1,-1,-0.136677139879544,-0.8860566476931629,-0.769551078621726,-0.6575773191777941,-0.337242168318426,-0.136677139879544,-0.0177287669604316,-0.244125144327509,-0.167491087293764,-0.10790539730952,-0.0915149811213503,-0.795880017344075,-0.853871964321762,-0.619788758288394,-0.795880017344075,-0.356547323513813,-0.387216143280265,-0.508638306165727,-0.102372908709559,-0.236572006437063,-0.920818753952375,-0.744727494896694,-0.677780705266081,-0.677780705266081,-0.481486060122113,-0.552841968657781,-0.823908740944319,-0.537602002101044,-0.236572006437063,-0.920818753952375,-1,-1,-0.769551078621726,-0.387216143280265,-0.08618614761628331],[-1,-1,-0.958607314841775,-0.552841968657781,-0.42021640338319,-0.0315170514460649,-0.387216143280265,-0.0132282657337552,-0.08618614761628331,-0.267606240177031,-0.292429823902064,-0.221848749616356,-0.09691001300805641,-0.455931955649724,-0.0555173278498314,-0.09691001300805641,-1,-1,-0.387216143280265,-0.638272163982407,-0.0655015487564323,-1,-0.397940008672038,-0.327902142064283,-1,-0.283996656365201,-0.236572006437063,-1,-0.387216143280265,-0.301029995663981,-1,-1,-0.677780705266081,-1,-1,0.0211892990699381,-0.154901959985743,-0.0268721464003014,-1,-1,-1,-1,-1,-0.602059991327962,-0.8860566476931629,-0.6575773191777941,-0.823908740944319,-0.920818753952375,-0.677780705266081,-0.0655015487564323,-0.0177287669604316,-0.0915149811213503,-0.0457574905606751,-1,-1,-1,-1,-1,-1,-0.42021640338319,-0.136677139879544,-1,-0.568636235841013,-0.119186407719209,-0.10790539730952,-0.468521082957745,-0.301029995663981,-0.823908740944319,-0.853871964321762,-1,-0.0457574905606751,-0.309803919971486,-0.958607314841775],[13.1498630136987,7.86986301369868,4.37986301369868,-4.53013698630132,-3.58013698630133,-7.02013698630132,0.34986301369868,-9.850136986301321,-4.87013698630132,-1.80013698630133,-3.90013698630132,-0.850136986301322,-7.17013698630132,-7.30013698630133,-9.800136986301331,-4.60013698630132,6.26986301369868,5.74986301369869,-3.48013698630132,-2.95013698630132,4.09986301369868,1.31986301369868,-5.22013698630131,-9.170136986301319,6.67986301369868,2.71986301369869,-4.07013698630132,6.84986301369868,5.46986301369869,-1.93013698630132,10.3498630136987,0.769863013698682,4.89986301369868,5.54986301369868,8.49986301369869,-1.90013698630132,5.94986301369867,-1.32013698630132,3.97986301369868,3.24986301369869,3.34986301369868,5.46986301369869,5.34986301369868,0.0798630136986844,0.0798630136986844,0.0698630136986793,-0.030136986301315,-0.40013698630132,-9.40013698630132,-9.570136986301319,-9.40013698630132,-10.4001369863013,-9.23013698630132,3.42986301369868,3.84986301369868,4.42986301369868,4.34986301369868,3.59986301369868,6.84986301369868,6.84986301369868,-8.070136986301319,9.34986301369868,-1.12013698630132,-1.58013698630133,-1.28013698630132,-8.90013698630132,-9.78013698630132,9.679863013698681,11.4298630136987,9.84986301369868,-8.78013698630132,-13.2001369863013,0.229863013698676],[6.29575342465754,7.21575342465754,5.67575342465754,3.84575342465754,6.79575342465754,-1.23424657534246,-7.48424657534246,-3.15424657534246,-4.80424657534246,0.715753424657542,7.64575342465754,-6.62424657534246,-6.77424657534246,5.22575342465754,-1.00424657534246,1.44575342465754,3.62575342465754,4.14575342465754,-10.5242465753425,3.42575342465754,-8.50424657534246,10.5957534246575,-7.13424657534246,-4.05424657534246,1.76575342465754,-8.10424657534246,3.64575342465754,-1.93424657534246,-3.00424657534246,4.92575342465754,-0.284246575342458,1.31575342465754,-1.58424657534245,0.0657534246575437,-0.944246575342461,-1.55424657534246,-4.83424657534245,-5.82424657534246,0.365753424657541,0.345753424657545,-0.224246575342455,-0.184246575342456,0.0157534246575395,5.71575342465754,5.76575342465754,5.77575342465754,5.74575342465754,5.37575342465754,3.39575342465754,-9.52424657534246,-11.1042465753425,-6.35424657534246,-8.77424657534246,-0.444246575342461,-0.0242465753424597,0.395753424657542,0.47575342465754,0.395753424657542,-1.60424657534246,-1.60424657534246,-9.85424657534246,0.22575342465754,1.01575342465754,1.14575342465754,1.96575342465754,9.765753424657539,7.64575342465754,-3.27424657534246,-4.10424657534246,-3.43424657534246,-1.35424657534246,5.29575342465754,12.0257534246575],[-0.0292293336836125,-0.0288084949659648,0.168066337472603,0.323799097855755,-0.0969099276503992,-0.311000816527614,-0.0780555900413767,-0.310602765835014,-0.103718215731708,-0.307346581428892,-0.09721776937832211,-0.141350847119886,0.244260808776541,0.152462598560019,-0.215446362920068,0.0771544361638787,-0.481468094865238,-0.324825738975867,-0.0291965152724669,0.277366229974973,0.0536068737786551,0.00769734056819287,0.0561412835453495,0.397643239435093,-0.541851922124491,0.00180811220815554,-0.109210452285235,0.285119229030982,0.402661464737253,-0.0892234658751334,0.34037601802153,0.101752899500749,-0.261088372878086,0.33410125220413,0.301391815787169,-0.341998700268382,-0.132979210880185,-0.185912642261525,0.40554829133539,-0.343998067150783,-0.195426680704331,-0.0793438535460617,0.228543162762895,0.138825990696476,0.255345598959894,0.0285677633287881,0.107694593530331,0.188687052409414,0.344738885478332,-0.0119727783865976,-0.022865289638083,0.0650124870253711,-0.0245082003781158,0.230170222498176,0.177036928859014,0.0326257006816087,0.434100725032423,0.303291434196138,-0.247825643563246,-0.071734384507565,0.152143103971937,-0.116407487533655,0.0219716781622865,-0.055346878121438,-0.363734243660454,-0.284475022304314,0.08954206947653991,-0.113074515647914,-0.113303486408655,-0.179271040873181,-0.200491781795241,0.0328354336939761,-0.120868984530917],[-0.09570940292468751,-0.0961302416423352,-0.233567886229035,-0.394380172141462,-0.269621616770014,-0.575055831165549,-0.921944409958623,-0.610215988117361,-0.720190525212611,-0.5165621595154271,-0.240024398940104,-0.858649152880114,-0.752899114942268,-0.367132763549252,-0.554104715701659,-0.48608982913738,-0.342440646079081,-0.313446425006541,-0.970803484727533,-0.402304966583273,-1.05360687377866,-0.012062145970643,-0.800868778442043,-0.641768383762602,-0.458148077875509,-1.00180811220816,-0.399427853880492,-0.694054622004483,-0.749448950961909,-0.330992937508057,-0.6000133285272859,-0.488969042781014,-0.6597303810742901,-0.563249240561986,-0.638633984105595,-0.616608614573393,-0.8670207891198149,-0.814087357738476,-0.5422254312149341,-0.54205858054238,-0.574124397917395,-0.5782334656317319,-0.565785331081321,-0.27550313057602,-0.273074365920326,-0.272692907656297,-0.275185680824095,-0.296592449718934,-0.436253866599683,-0.783907238957477,-0.8310066746836789,-0.684801245313765,-0.771371816965959,-0.586717546011989,-0.564253072139279,-0.541264006847336,-0.536473633741982,-0.539863440633201,-0.672993110389129,-0.672993110389129,-0.829923809238019,-0.561373217732426,-0.503457738284399,-0.497495090536343,-0.460174497283865,-0.25312697979673,-0.326114075913603,-0.807744238304461,-0.886696513591345,-0.82072895912682,-0.569059296826485,-0.420051576974241,0.034682836914634]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>C3<\/th>\n      <th>C4<\/th>\n      <th>MAP<\/th>\n      <th>MAT<\/th>\n      <th>JJAMAP<\/th>\n      <th>DJFMAP<\/th>\n      <th>LONG<\/th>\n      <th>LAT<\/th>\n      <th>LC3<\/th>\n      <th>LC4<\/th>\n      <th>CLONG<\/th>\n      <th>CLAT<\/th>\n      <th>RESID1<\/th>\n      <th>PREDICT1<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5,6,7,8,9,10,11,12,13,14]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"C3","targets":1},{"name":"C4","targets":2},{"name":"MAP","targets":3},{"name":"MAT","targets":4},{"name":"JJAMAP","targets":5},{"name":"DJFMAP","targets":6},{"name":"LONG","targets":7},{"name":"LAT","targets":8},{"name":"LC3","targets":9},{"name":"LC4","targets":10},{"name":"CLONG","targets":11},{"name":"CLAT","targets":12},{"name":"RESID1","targets":13},{"name":"PREDICT1","targets":14}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="distribution-of-c3" class="level4">
<h4 class="anchored" data-anchor-id="distribution-of-c3">Distribution of C3</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>C3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mutiple_linear_regression_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The relative abundance of <span class="math inline">\(C_3\)</span> plants was positively skewed and transformed to <span class="math inline">\(log_{10} + 0.1\)</span> (<span class="math inline">\(log_{10}C_3\)</span>). A correlation matrix between the predictor variables indicated that some predictors are strongly correlated.</p>
<p>The transformation is seen in the column <code>LC3</code>.</p>
<p>If not, we could have transformed this way in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log10</span>(df<span class="sc">$</span>C3 <span class="sc">+</span> <span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -0.124938737 -0.124938737 -0.065501549 -0.070581074 -0.366531544
 [6] -0.886056648 -1.000000000 -0.920818754 -0.823908741 -0.823908741
[11] -0.337242168 -1.000000000 -0.508638306 -0.214670165 -0.769551079
[16] -0.408935393 -0.823908741 -0.638272164 -1.000000000 -0.124938737
[21] -1.000000000 -0.004364805 -0.744727495 -0.244125144 -1.000000000
[26] -1.000000000 -0.508638306 -0.408935393 -0.346787486 -0.420216403
[31] -0.259637311 -0.387216143 -0.920818754 -0.229147988 -0.337242168
[36] -0.958607315 -1.000000000 -1.000000000 -0.136677140 -0.886056648
[41] -0.769551079 -0.657577319 -0.337242168 -0.136677140 -0.017728767
[46] -0.244125144 -0.167491087 -0.107905397 -0.091514981 -0.795880017
[51] -0.853871964 -0.619788758 -0.795880017 -0.356547324 -0.387216143
[56] -0.508638306 -0.102372909 -0.236572006 -0.920818754 -0.744727495
[61] -0.677780705 -0.677780705 -0.481486060 -0.552841969 -0.823908741
[66] -0.537602002 -0.236572006 -0.920818754 -1.000000000 -1.000000000
[71] -0.769551079 -0.387216143 -0.086186148</code></pre>
</div>
</div>
</section>
<section id="distribution-of-lc3-y-variable" class="level4">
<h4 class="anchored" data-anchor-id="distribution-of-lc3-y-variable">Distribution of LC3 (Y variable)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>LC3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mutiple_linear_regression_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="correlation-matrix-plot-between-the-predictors" class="level4">
<h4 class="anchored" data-anchor-id="correlation-matrix-plot-between-the-predictors">Correlation matrix (plot) between the predictors</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"PerformanceAnalytics"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chart.Correlation</span>(df[,<span class="dv">3</span><span class="sc">:</span><span class="dv">8</span>], <span class="at">histogram=</span><span class="cn">TRUE</span>, <span class="at">pch=</span><span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mutiple_linear_regression_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="correlation-matrix-between-the-predictors" class="level4">
<h4 class="anchored" data-anchor-id="correlation-matrix-between-the-predictors">Correlation matrix between the predictors</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df[,<span class="fu">c</span>(<span class="st">"LAT"</span>,<span class="st">"LONG"</span>,<span class="st">"MAP"</span>,<span class="st">"MAT"</span>,<span class="st">"JJAMAP"</span>,<span class="st">"DJFMAP"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               LAT        LONG        MAP          MAT      JJAMAP       DJFMAP
LAT     1.00000000  0.09655281 -0.2465058 -0.838590413  0.07417497 -0.065124848
LONG    0.09655281  1.00000000 -0.7336870 -0.213109100 -0.49155774  0.770743994
MAP    -0.24650582 -0.73368703  1.0000000  0.355090766  0.11225905 -0.404512409
MAT    -0.83859041 -0.21310910  0.3550908  1.000000000 -0.08077131  0.001478037
JJAMAP  0.07417497 -0.49155774  0.1122590 -0.080771307  1.00000000 -0.791540381
DJFMAP -0.06512485  0.77074399 -0.4045124  0.001478037 -0.79154038  1.000000000</code></pre>
</div>
</div>
<p>A correlation matrix between the predictor variables indicated that some predictors are <strong>strongly correlated</strong>.</p>
<table class="table">
<tbody>
<tr class="odd">
<td></td>
<td>LAT</td>
<td>LONG</td>
<td>MAP</td>
<td>MAT</td>
<td>JJAMAP</td>
<td>DJFMAP</td>
</tr>
<tr class="even">
<td>LAT</td>
<td>1.000</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>LONG</td>
<td>0.097</td>
<td>1.000</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>MAP</td>
<td>-0.247</td>
<td>-0.734</td>
<td>1.000</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>MAT</td>
<td>-0.839</td>
<td>-0.213</td>
<td>0.355</td>
<td>1.000</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>JJAMAP</td>
<td>0.074</td>
<td>-0.492</td>
<td>0.112</td>
<td>-0.081</td>
<td>1.000</td>
<td></td>
</tr>
<tr class="odd">
<td>DJFMAP</td>
<td>-0.065</td>
<td>0.771</td>
<td>-0.405</td>
<td>0.001</td>
<td>-0.792</td>
<td>1.000</td>
</tr>
</tbody>
</table>
<p>Note the <strong>high correlations</strong> between LAT and MAT, LONG and MAP, and JJAMAP and DJFMAP, suggesting that <strong>collinearity</strong> may be a problem with this analysis.</p>
</section>
<section id="model-1-additive-model" class="level4">
<h4 class="anchored" data-anchor-id="model-1-additive-model">Model 1: additive model</h4>
<p>With six predictor variables, a linear model with all possible interactions would have 64 model terms (plus an intercept) including four-, five- and six-way interactions that are extremely difficult to interpret. As a first pass, we fitted an additive model:</p>
<p><span class="math display">\[(log_{10}C_3) = \beta_0 + \beta_1(LAT)_i + \beta_2(LONG)_i + \beta_3(MAP)_i + \beta_4(MAT)_i + \beta_5(JJAMAP)_i + \beta_6(DJFMAP)_i + \epsilon_i\]</span></p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 27%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Standard error</th>
<th>Standardized coefficient</th>
<th>Tolerance</th>
<th>t</th>
<th>P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-2.689</td>
<td>1.239</td>
<td>0</td>
<td></td>
<td>-2.170</td>
<td>0.034</td>
</tr>
<tr class="even">
<td>LAT</td>
<td>0.043</td>
<td>0.010</td>
<td>0.703</td>
<td>0.285</td>
<td>4.375</td>
<td>&lt;0.001</td>
</tr>
<tr class="odd">
<td>LONG</td>
<td>0.007</td>
<td>0.010</td>
<td>0.136</td>
<td>0.190</td>
<td>0.690</td>
<td>0.942</td>
</tr>
<tr class="even">
<td>MAP</td>
<td>&lt;0.001</td>
<td>&lt;0.001</td>
<td>0.181</td>
<td>0.357</td>
<td>1.261</td>
<td>0.212</td>
</tr>
<tr class="odd">
<td>MAT</td>
<td>-0.001</td>
<td>0.012</td>
<td>-0.012</td>
<td>0.267</td>
<td>-0.073</td>
<td>0.942</td>
</tr>
<tr class="even">
<td>JJAMAP</td>
<td>-0.834</td>
<td>0.475</td>
<td>-0.268</td>
<td>0.316</td>
<td>-1.755</td>
<td>0.084</td>
</tr>
<tr class="odd">
<td>DJFMAP</td>
<td>-0.962</td>
<td>0.716</td>
<td>-0.275</td>
<td>0.175</td>
<td>-1.343</td>
<td>0.184</td>
</tr>
</tbody>
</table>
<p><strong>Let’s do the same thing in R!</strong></p>
</section>
<section id="model-1-all-the-explanatory-variables" class="level4">
<h4 class="anchored" data-anchor-id="model-1-all-the-explanatory-variables">Model 1: all the explanatory variables</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LC3 <span class="sc">~</span> LAT <span class="sc">+</span> LONG <span class="sc">+</span> MAP <span class="sc">+</span> MAT <span class="sc">+</span> JJAMAP <span class="sc">+</span> DJFMAP, <span class="at">data =</span> df)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LC3 ~ LAT + LONG + MAP + MAT + JJAMAP + DJFMAP, 
    data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.55607 -0.17084  0.02938  0.18397  0.47953 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.6886133  1.2391496  -2.170   0.0336 *  
LAT          0.0434331  0.0099285   4.375 4.42e-05 ***
LONG         0.0069236  0.0100330   0.690   0.4926    
MAP          0.0002743  0.0002175   1.261   0.2117    
MAT         -0.0008468  0.0116261  -0.073   0.9422    
JJAMAP      -0.8338536  0.4750796  -1.755   0.0839 .  
DJFMAP      -0.9618361  0.7163073  -1.343   0.1839    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2387 on 66 degrees of freedom
Multiple R-squared:  0.5136,    Adjusted R-squared:  0.4694 
F-statistic: 11.61 on 6 and 66 DF,  p-value: 7.787e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: LC3
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
LAT        1 3.5703  3.5703 62.6573 3.749e-11 ***
LONG       1 0.0412  0.0412  0.7238   0.39796    
MAP        1 0.1818  0.1818  3.1901   0.07868 .  
MAT        1 0.0002  0.0002  0.0036   0.95224    
JJAMAP     1 0.0745  0.0745  1.3066   0.25714    
DJFMAP     1 0.1027  0.1027  1.8030   0.18395    
Residuals 66 3.7608  0.0570                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Final equation for the model 1 (All the variables):</p>
<div class="cell">
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{LC3} = \beta_{0} + \beta_{1}(\operatorname{LAT}) + \beta_{2}(\operatorname{LONG}) + \beta_{3}(\operatorname{MAP}) + \beta_{4}(\operatorname{MAT}) + \beta_{5}(\operatorname{JJAMAP}) + \beta_{6}(\operatorname{DJFMAP}) + \epsilon
\]</span></p>
</div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{LC3}} = -2.69 + 0.04(\operatorname{LAT}) + 0.01(\operatorname{LONG}) + 0(\operatorname{MAP}) + 0(\operatorname{MAT}) - 0.83(\operatorname{JJAMAP}) - 0.96(\operatorname{DJFMAP})
\]</span></p>
</div>
</div>
</section>
<section id="tolerance" class="level4">
<h4 class="anchored" data-anchor-id="tolerance">Tolerance</h4>
<p>In multiple regression analysis, <strong>Variance Inflation Factor (VIF)</strong> and <strong>Tolerance</strong> are both used to detect multicollinearity, a condition where independent variables are highly correlated. Here’s what they represent:</p>
<section id="variance-inflation-factor-vif" class="level5">
<h5 class="anchored" data-anchor-id="variance-inflation-factor-vif"><strong>Variance Inflation Factor (VIF):</strong></h5>
<ul>
<li><p><strong>Definition</strong>: VIF measures how much the variance of a regression coefficient is inflated due to multicollinearity among the predictor variables. The higher the VIF, the more collinear the variable is with others.</p></li>
<li><p><strong>Interpretation</strong>:</p>
<ul>
<li><p><strong>VIF = 1</strong>: No correlation between the predictor and the other variables.</p></li>
<li><p><strong>VIF between 1 and 5</strong>: Moderate correlation; not usually a cause for concern.</p></li>
<li><p><strong>VIF &gt; 5 or 10</strong>: High correlation; multicollinearity might be a problem that could distort the results.</p></li>
</ul></li>
</ul>
</section>
<section id="tolerance-1" class="level5">
<h5 class="anchored" data-anchor-id="tolerance-1"><strong>Tolerance</strong>:</h5>
<ul>
<li><p><strong>Definition</strong>: Tolerance is the reciprocal of VIF and measures the proportion of variance in a predictor that is not explained by the other predictors. It indicates how much of the variability of the independent variable is unique.</p>
<p>Tolerance = 1/VIF​</p></li>
<li><p><strong>Interpretation</strong>:</p>
<ul>
<li><p><strong>Tolerance near 1</strong>: Little or no multicollinearity.</p></li>
<li><p><strong>Tolerance &lt; 0.2 or 0.1</strong>: Indicates potential multicollinearity issues.</p></li>
</ul></li>
</ul>
</section>
<section id="relationship" class="level5">
<h5 class="anchored" data-anchor-id="relationship">Relationship:</h5>
<ul>
<li>When <strong>VIF is large</strong>, <strong>Tolerance is small</strong>.</li>
</ul>
<p>For example, if VIF is 5, Tolerance will be 0.2. If VIF is 10, Tolerance will be 0.1. Both VIF and Tolerance help in diagnosing multicollinearity, but using one is usually enough as they are inversely related.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Variance Inflation Factors (VIF)</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     LAT     LONG      MAP      MAT   JJAMAP   DJFMAP 
3.502732 5.267618 2.799428 3.742780 3.163215 5.710315 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tolerance</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tolerance <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">vif</span>(model1)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>tolerance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      LAT      LONG       MAP       MAT    JJAMAP    DJFMAP 
0.2854914 0.1898391 0.3572159 0.2671810 0.3161340 0.1751217 </code></pre>
</div>
</div>
<p>It is clear that collinearity is a problem with tolerances for two of the predictors (LONG &amp; DJFMAP) approaching 0.1.</p>
</section>
</section>
<section id="model-2-with-interaction" class="level4">
<h4 class="anchored" data-anchor-id="model-2-with-interaction">Model 2: with interaction</h4>
<p>Paruelo &amp; Lauenroth (1996) separated the predictors into two groups their analyses. <strong>One group included LAT and LONG and the other included MAP, MAT, JJAMAP and DJFMAP.</strong> We will focus on the relationship between log-transformed relative abundance of <span class="math inline">\(C_3\)</span> plants and latitude and longitude. We fitted a multiplicative model including an interaction term that measured how the relationship between <span class="math inline">\(C_3\)</span> plants and latitude could vary with longitude and vice versa:</p>
<p><span class="math inline">\((log_{10}C_3)_i = \beta_0 + \beta_1(LAT)_i + \beta_2(LONG)_i + \beta_3(LAT\times LONG)_i + \epsilon_i\)</span></p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Standard error</th>
<th>Tolerance</th>
<th>t</th>
<th>P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>7.391</td>
<td>3625</td>
<td></td>
<td>2.039</td>
<td>0.045</td>
</tr>
<tr class="even">
<td>LAT</td>
<td>-0.191</td>
<td>0.091</td>
<td>0.003</td>
<td>-2.102</td>
<td>0.039</td>
</tr>
<tr class="odd">
<td>LONG</td>
<td>-0.093</td>
<td>0.035</td>
<td>0.015</td>
<td>-2.659</td>
<td>0.010</td>
</tr>
<tr class="even">
<td>LAT <span class="math inline">\(\times\)</span> LONG</td>
<td>0.002</td>
<td>0.001</td>
<td>0.002</td>
<td>2.572</td>
<td>0.012</td>
</tr>
</tbody>
</table>
<p><strong>Let’s do that in R!</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LC3 <span class="sc">~</span> LAT<span class="sc">*</span>LONG, <span class="at">data =</span> df)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LC3 ~ LAT * LONG, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.54185 -0.13298 -0.02287  0.16807  0.43410 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  7.3909798  3.6253486   2.039  0.04531 * 
LAT         -0.1912401  0.0910018  -2.101  0.03925 * 
LONG        -0.0929020  0.0349331  -2.659  0.00972 **
LAT:LONG     0.0022522  0.0008757   2.572  0.01227 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2334 on 69 degrees of freedom
Multiple R-squared:  0.5137,    Adjusted R-squared:  0.4926 
F-statistic:  24.3 on 3 and 69 DF,  p-value: 7.657e-11</code></pre>
</div>
</div>
<p>Final equation for the model 2 (Interaction):</p>
<div class="cell">
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{LC3} = \beta_{0} + \beta_{1}(\operatorname{LAT}) + \beta_{2}(\operatorname{LONG}) + \beta_{3}(\operatorname{LAT} \times \operatorname{LONG}) + \epsilon
\]</span></p>
</div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{LC3}} = 7.39 - 0.19(\operatorname{LAT}) - 0.09(\operatorname{LONG}) + 0(\operatorname{LAT} \times \operatorname{LONG})
\]</span></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tolerance</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span>car<span class="sc">::</span><span class="fu">vif</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        LAT        LONG    LAT:LONG 
0.003249445 0.014973575 0.002494144 </code></pre>
</div>
</div>
<p>Note the very low tolerances indicating high correlations between the predictor variables and their interactions. An indication of the effect of collinearity is that if we omit the interaction and refit the model, the partial regression slope for latitude changes sign.</p>
</section>
<section id="model-3-centering-and-interaction" class="level4">
<h4 class="anchored" data-anchor-id="model-3-centering-and-interaction">Model 3: centering and interaction</h4>
<p>We refitted the multiplicative model after centering both LAT and LONG.</p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Standard error</th>
<th>Tolerance</th>
<th>t</th>
<th>P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-0.553</td>
<td>0.027</td>
<td></td>
<td>20.130</td>
<td>&lt;0.001</td>
</tr>
<tr class="even">
<td>LAT</td>
<td>0.048</td>
<td>0.006</td>
<td>0.829</td>
<td>8.483</td>
<td>&lt;0.001</td>
</tr>
<tr class="odd">
<td>LONG</td>
<td>-0.003</td>
<td>0.004</td>
<td>0.980</td>
<td>-0.597</td>
<td>0.552</td>
</tr>
<tr class="even">
<td>LAT <span class="math inline">\(\times\)</span> LONG</td>
<td>0.002</td>
<td>0.001</td>
<td>0.820</td>
<td>2.572</td>
<td>0.012</td>
</tr>
</tbody>
</table>
<p><strong>Let’s do that in R!</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># center the variables LONG and LAT</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># note: the function c() was used only to structure the values from column to row </span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># to occupy less space in the screen.</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">scale</span>(df<span class="sc">$</span>LONG, <span class="at">scale =</span> F))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  13.14986301   7.86986301   4.37986301  -4.53013699  -3.58013699
 [6]  -7.02013699   0.34986301  -9.85013699  -4.87013699  -1.80013699
[11]  -3.90013699  -0.85013699  -7.17013699  -7.30013699  -9.80013699
[16]  -4.60013699   6.26986301   5.74986301  -3.48013699  -2.95013699
[21]   4.09986301   1.31986301  -5.22013699  -9.17013699   6.67986301
[26]   2.71986301  -4.07013699   6.84986301   5.46986301  -1.93013699
[31]  10.34986301   0.76986301   4.89986301   5.54986301   8.49986301
[36]  -1.90013699   5.94986301  -1.32013699   3.97986301   3.24986301
[41]   3.34986301   5.46986301   5.34986301   0.07986301   0.07986301
[46]   0.06986301  -0.03013699  -0.40013699  -9.40013699  -9.57013699
[51]  -9.40013699 -10.40013699  -9.23013699   3.42986301   3.84986301
[56]   4.42986301   4.34986301   3.59986301   6.84986301   6.84986301
[61]  -8.07013699   9.34986301  -1.12013699  -1.58013699  -1.28013699
[66]  -8.90013699  -9.78013699   9.67986301  11.42986301   9.84986301
[71]  -8.78013699 -13.20013699   0.22986301</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">scale</span>(df<span class="sc">$</span>LAT, <span class="at">scale =</span> F))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]   6.29575342   7.21575342   5.67575342   3.84575342   6.79575342
 [6]  -1.23424658  -7.48424658  -3.15424658  -4.80424658   0.71575342
[11]   7.64575342  -6.62424658  -6.77424658   5.22575342  -1.00424658
[16]   1.44575342   3.62575342   4.14575342 -10.52424658   3.42575342
[21]  -8.50424658  10.59575342  -7.13424658  -4.05424658   1.76575342
[26]  -8.10424658   3.64575342  -1.93424658  -3.00424658   4.92575342
[31]  -0.28424658   1.31575342  -1.58424658   0.06575342  -0.94424658
[36]  -1.55424658  -4.83424658  -5.82424658   0.36575342   0.34575342
[41]  -0.22424658  -0.18424658   0.01575342   5.71575342   5.76575342
[46]   5.77575342   5.74575342   5.37575342   3.39575342  -9.52424658
[51] -11.10424658  -6.35424658  -8.77424658  -0.44424658  -0.02424658
[56]   0.39575342   0.47575342   0.39575342  -1.60424658  -1.60424658
[61]  -9.85424658   0.22575342   1.01575342   1.14575342   1.96575342
[66]   9.76575342   7.64575342  -3.27424658  -4.10424658  -3.43424658
[71]  -1.35424658   5.29575342  12.02575342</code></pre>
</div>
</div>
<p>However, these columns are already present in the dataset as <code>CLAT</code> and <code>CLONG</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LC3 <span class="sc">~</span> CLAT<span class="sc">*</span>CLONG, <span class="at">data =</span> df)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LC3 ~ CLAT * CLONG, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.54185 -0.13298 -0.02287  0.16807  0.43410 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.5529416  0.0274679 -20.130  &lt; 2e-16 ***
CLAT         0.0483954  0.0057047   8.483 2.61e-12 ***
CLONG       -0.0025787  0.0043182  -0.597   0.5523    
CLAT:CLONG   0.0022522  0.0008757   2.572   0.0123 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2334 on 69 degrees of freedom
Multiple R-squared:  0.5137,    Adjusted R-squared:  0.4926 
F-statistic:  24.3 on 3 and 69 DF,  p-value: 7.657e-11</code></pre>
</div>
</div>
<p>Final equation for the model 3 (Interaction):</p>
<div class="cell">
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{LC3} = \beta_{0} + \beta_{1}(\operatorname{CLAT}) + \beta_{2}(\operatorname{CLONG}) + \beta_{3}(\operatorname{CLAT} \times \operatorname{CLONG}) + \epsilon
\]</span></p>
</div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{LC3}} = -0.55 + 0.05(\operatorname{CLAT}) + 0(\operatorname{CLONG}) + 0(\operatorname{CLAT} \times \operatorname{CLONG})
\]</span></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tolerance</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span>car<span class="sc">::</span><span class="fu">vif</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      CLAT      CLONG CLAT:CLONG 
 0.8268942  0.9799097  0.8195915 </code></pre>
</div>
</div>
<p>Now the collinearity problem has disappeared.</p>
</section>
<section id="diagnostic-plots" class="level4">
<h4 class="anchored" data-anchor-id="diagnostic-plots">Diagnostic plots</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mutiple_linear_regression_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Diagnostic checks of the model did not reveal any outliers nor influential values.</p>
</section>
<section id="boxplot-of-residuals" class="level4">
<h4 class="anchored" data-anchor-id="boxplot-of-residuals">Boxplot of residuals</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(model3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mutiple_linear_regression_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The boxplot of residuals was reasonably symmetrical and although there was some heterogeneity in spread of residuals when plotted against predicted values, and a <span class="math inline">\(45°\)</span> line representing sites with zero abundance of <span class="math inline">\(C_3\)</span> plants, this was not of a form that could be simply corrected (Figure 6.2).</p>
</section>
<section id="model-4-stepwise-selection" class="level4">
<h4 class="anchored" data-anchor-id="model-4-stepwise-selection">Model 4: stepwise selection</h4>
<p>Stepwise selection is a method used in regression analysis to select the most significant predictors for a model. It involves adding or removing variables iteratively based on specific criteria, such as p-values, AIC (Akaike Information Criterion), or adjusted R². There are three main types: <strong>forward selection</strong>, which starts with no variables and adds them one by one; <strong>backward elimination</strong>, which starts with all variables and removes the least significant ones; and <strong>stepwise selection</strong>, which combines both forward and backward methods, adding or removing variables at each step. The goal is to find a balance between model simplicity and explanatory power.</p>
<p>We’ll use the function <code>step()</code>, with the argument:</p>
<ul>
<li><p><code>direction = "both"</code> for stepwise selection</p></li>
<li><p><code>direction = "backward"</code> for backward selection</p></li>
<li><p><code>direction = "forward"</code> for forward selection</p></li>
</ul>
<p>Out of interest, we also ran the full model with all six predictors through both a forward and backward selection routine for stepwise multiple regression. For both methods, the significance level for entering and removing terms based on partial F statistics was set at 0.15.</p>
</section>
<section id="backward-selection" class="level4">
<h4 class="anchored" data-anchor-id="backward-selection">Backward selection</h4>
<p>The backward selection is as follows.</p>
<table class="table">
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Standard error</th>
<th>t</th>
<th>P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>JJAMAP</td>
<td>-1.002</td>
<td>0.433</td>
<td>-2.314</td>
<td>0.024</td>
</tr>
<tr class="even">
<td>DJFMAP</td>
<td>-1.005</td>
<td>0.485</td>
<td>-2.070</td>
<td>0.042</td>
</tr>
<tr class="odd">
<td>LAT</td>
<td>0.042</td>
<td>0.005</td>
<td>8.033</td>
<td>&lt;0.001</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># we use an additive model with 6 explicative variables</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LC3 <span class="sc">~</span> MAP <span class="sc">+</span> MAT <span class="sc">+</span> JJAMAP <span class="sc">+</span> DJFMAP <span class="sc">+</span> LONG <span class="sc">+</span> LAT, <span class="at">data =</span> df)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># we apply the backward selection</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">step</span>(model4, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">test =</span> <span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-202.51
LC3 ~ MAP + MAT + JJAMAP + DJFMAP + LONG + LAT

         Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
- MAT     1   0.00030 3.7611 -204.50  0.0053   0.94215    
- LONG    1   0.02714 3.7879 -203.98  0.4762   0.49256    
- MAP     1   0.09065 3.8514 -202.77  1.5908   0.21165    
- DJFMAP  1   0.10274 3.8635 -202.54  1.8030   0.18395    
&lt;none&gt;                3.7608 -202.51                      
- JJAMAP  1   0.17554 3.9363 -201.18  3.0807   0.08387 .  
- LAT     1   1.09047 4.8513 -185.92 19.1371 4.424e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step:  AIC=-204.5
LC3 ~ MAP + JJAMAP + DJFMAP + LONG + LAT

         Df Sum of Sq    RSS     AIC F value   Pr(&gt;F)    
- LONG    1    0.0282 3.7893 -205.96  0.5019  0.48111    
- MAP     1    0.0904 3.8515 -204.76  1.6108  0.20877    
- DJFMAP  1    0.1030 3.8641 -204.53  1.8346  0.18014    
&lt;none&gt;                3.7611 -204.50                     
- JJAMAP  1    0.1756 3.9367 -203.17  3.1280  0.08151 .  
- LAT     1    3.5320 7.2931 -158.16 62.9183 3.19e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step:  AIC=-205.95
LC3 ~ MAP + JJAMAP + DJFMAP + LAT

         Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
- MAP     1    0.0643 3.8535 -206.73  1.1535   0.28661    
- DJFMAP  1    0.0753 3.8646 -206.52  1.3517   0.24905    
&lt;none&gt;                3.7893 -205.96                      
- JJAMAP  1    0.1682 3.9575 -204.78  3.0192   0.08681 .  
- LAT     1    3.5512 7.3404 -159.69 63.7272 2.353e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step:  AIC=-206.73
LC3 ~ JJAMAP + DJFMAP + LAT

         Df Sum of Sq    RSS     AIC F value    Pr(&gt;F)    
&lt;none&gt;                3.8535 -206.73                      
- DJFMAP  1    0.2393 4.0929 -204.33  4.2856   0.04218 *  
- JJAMAP  1    0.2990 4.1526 -203.27  5.3542   0.02366 *  
- LAT     1    3.6041 7.4577 -160.53 64.5343 1.737e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LC3 ~ JJAMAP + DJFMAP + LAT, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.55475 -0.16509  0.02634  0.18400  0.48787 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -1.724723   0.305825  -5.640 3.46e-07 ***
JJAMAP      -1.001984   0.433027  -2.314   0.0237 *  
DJFMAP      -1.005341   0.485632  -2.070   0.0422 *  
LAT          0.042309   0.005267   8.033 1.74e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2363 on 69 degrees of freedom
Multiple R-squared:  0.5016,    Adjusted R-squared:  0.4799 
F-statistic: 23.15 on 3 and 69 DF,  p-value: 1.775e-10</code></pre>
</div>
</div>
<p>Final equation for the model 4 (Backward):</p>
<div class="cell">
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{LC3} = \beta_{0} + \beta_{1}(\operatorname{JJAMAP}) + \beta_{2}(\operatorname{DJFMAP}) + \beta_{3}(\operatorname{LAT}) + \epsilon
\]</span></p>
</div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{LC3}} = -1.72 - 1(\operatorname{JJAMAP}) - 1.01(\operatorname{DJFMAP}) + 0.04(\operatorname{LAT})
\]</span></p>
</div>
</div>
<p>The forward selection is as follows.</p>
<table class="table">
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Standard error</th>
<th>t</th>
<th>P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MAP</td>
<td>&lt;0.001</td>
<td>&lt;0.001</td>
<td>1.840</td>
<td>0.070</td>
</tr>
<tr class="even">
<td>LAT</td>
<td>0.044</td>
<td>0.005</td>
<td>66.319</td>
<td>&lt;0.001</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># we use an additive model with 6 explicative variables</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LC3 <span class="sc">~</span> MAP <span class="sc">+</span> MAT <span class="sc">+</span> JJAMAP <span class="sc">+</span> DJFMAP <span class="sc">+</span> LONG <span class="sc">+</span> LAT, <span class="at">data =</span> df)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># we apply the forward selection</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">step</span>(model4, <span class="at">direction =</span> <span class="st">"forward"</span>, <span class="at">test =</span> <span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-202.51
LC3 ~ MAP + MAT + JJAMAP + DJFMAP + LONG + LAT</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LC3 ~ MAP + MAT + JJAMAP + DJFMAP + LONG + LAT, 
    data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.55607 -0.17084  0.02938  0.18397  0.47953 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.6886133  1.2391496  -2.170   0.0336 *  
MAP          0.0002743  0.0002175   1.261   0.2117    
MAT         -0.0008468  0.0116261  -0.073   0.9422    
JJAMAP      -0.8338536  0.4750796  -1.755   0.0839 .  
DJFMAP      -0.9618361  0.7163073  -1.343   0.1839    
LONG         0.0069236  0.0100330   0.690   0.4926    
LAT          0.0434331  0.0099285   4.375 4.42e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2387 on 66 degrees of freedom
Multiple R-squared:  0.5136,    Adjusted R-squared:  0.4694 
F-statistic: 11.61 on 6 and 66 DF,  p-value: 7.787e-09</code></pre>
</div>
</div>
<p>Final equation for the model 4 (Forward):</p>
<div class="cell">
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{LC3} = \beta_{0} + \beta_{1}(\operatorname{MAP}) + \beta_{2}(\operatorname{MAT}) + \beta_{3}(\operatorname{JJAMAP}) + \beta_{4}(\operatorname{DJFMAP}) + \beta_{5}(\operatorname{LONG}) + \beta_{6}(\operatorname{LAT}) + \epsilon
\]</span></p>
</div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{LC3}} = -2.69 + 0(\operatorname{MAP}) + 0(\operatorname{MAT}) - 0.83(\operatorname{JJAMAP}) - 0.96(\operatorname{DJFMAP}) + 0.01(\operatorname{LONG}) + 0.04(\operatorname{LAT})
\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The results in R differ from those in the book because it used different metrics to select the best model. The book uses an F-test set at 0.15.</p>
</div>
</div>
</section>
<section id="metrics-aic-and-bic-for-variable-selection" class="level4">
<h4 class="anchored" data-anchor-id="metrics-aic-and-bic-for-variable-selection">Metrics AIC and BIC for variable selection</h4>
<p><strong>Akaike Information Criterion (AIC)</strong> and <strong>Bayesian Information Criterion (BIC)</strong> are statistical measures used for model selection, particularly in the context of regression and other predictive models. Both criteria penalize model complexity to prevent overfitting, but they do so differently: AIC is based on the concept of information loss, favoring models that minimize the information loss between the true model and the approximating model, while BIC incorporates a stronger penalty for the number of parameters as the sample size increases, making it more conservative in terms of model complexity. Specifically, AIC is calculated as</p>
<p>AIC = <span class="math inline">\(-2log(L) + 2k\)</span> (where (<span class="math inline">\(L\)</span>) is the likelihood of the model and (<span class="math inline">\(k\)</span>) is the number of parameters), whereas BIC is computed as</p>
<p>BIC = <span class="math inline">\(-2log(L) + k \space log(n)\)</span> (where (<span class="math inline">\(n\)</span>) is the sample size).</p>
<p>In practice, <strong>lower values of</strong> <strong>AIC or BIC indicate a better-fitting model</strong>, with AIC often used for predictive performance and BIC more frequently used for model selection when the goal is to identify the true model structure.</p>
</section>
<section id="model-5-aic-for-selecting-the-best-model" class="level4">
<h4 class="anchored" data-anchor-id="model-5-aic-for-selecting-the-best-model">Model 5: AIC for selecting the best model</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LC3 <span class="sc">~</span> MAP <span class="sc">+</span> MAT <span class="sc">+</span> JJAMAP <span class="sc">+</span> DJFMAP <span class="sc">+</span> LONG <span class="sc">+</span> LAT, <span class="at">data =</span> df)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># we select k = 2 to represent AIC </span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>model5_AIC <span class="ot">&lt;-</span> <span class="fu">step</span>(model5, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">k =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-202.51
LC3 ~ MAP + MAT + JJAMAP + DJFMAP + LONG + LAT

         Df Sum of Sq    RSS     AIC
- MAT     1   0.00030 3.7611 -204.50
- LONG    1   0.02714 3.7879 -203.98
- MAP     1   0.09065 3.8514 -202.77
- DJFMAP  1   0.10274 3.8635 -202.54
&lt;none&gt;                3.7608 -202.51
- JJAMAP  1   0.17554 3.9363 -201.18
- LAT     1   1.09047 4.8513 -185.92

Step:  AIC=-204.5
LC3 ~ MAP + JJAMAP + DJFMAP + LONG + LAT

         Df Sum of Sq    RSS     AIC
- LONG    1    0.0282 3.7893 -205.96
- MAP     1    0.0904 3.8515 -204.76
- DJFMAP  1    0.1030 3.8641 -204.53
&lt;none&gt;                3.7611 -204.50
- JJAMAP  1    0.1756 3.9367 -203.17
- LAT     1    3.5320 7.2931 -158.16

Step:  AIC=-205.95
LC3 ~ MAP + JJAMAP + DJFMAP + LAT

         Df Sum of Sq    RSS     AIC
- MAP     1    0.0643 3.8535 -206.73
- DJFMAP  1    0.0753 3.8646 -206.52
&lt;none&gt;                3.7893 -205.96
- JJAMAP  1    0.1682 3.9575 -204.78
- LAT     1    3.5512 7.3404 -159.69

Step:  AIC=-206.73
LC3 ~ JJAMAP + DJFMAP + LAT

         Df Sum of Sq    RSS     AIC
&lt;none&gt;                3.8535 -206.73
- DJFMAP  1    0.2393 4.0929 -204.33
- JJAMAP  1    0.2990 4.1526 -203.27
- LAT     1    3.6041 7.4577 -160.53</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># final model with the best AIC</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model5_AIC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LC3 ~ JJAMAP + DJFMAP + LAT, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.55475 -0.16509  0.02634  0.18400  0.48787 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -1.724723   0.305825  -5.640 3.46e-07 ***
JJAMAP      -1.001984   0.433027  -2.314   0.0237 *  
DJFMAP      -1.005341   0.485632  -2.070   0.0422 *  
LAT          0.042309   0.005267   8.033 1.74e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2363 on 69 degrees of freedom
Multiple R-squared:  0.5016,    Adjusted R-squared:  0.4799 
F-statistic: 23.15 on 3 and 69 DF,  p-value: 1.775e-10</code></pre>
</div>
</div>
<p>Final equation for the model 5 (AIC - backward):</p>
<div class="cell">
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{LC3} = \beta_{0} + \beta_{1}(\operatorname{JJAMAP}) + \beta_{2}(\operatorname{DJFMAP}) + \beta_{3}(\operatorname{LAT}) + \epsilon
\]</span></p>
</div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{LC3}} = -1.72 - 1(\operatorname{JJAMAP}) - 1.01(\operatorname{DJFMAP}) + 0.04(\operatorname{LAT})
\]</span></p>
</div>
</div>
<section id="applying-bic-for-selecting-the-best-model" class="level5">
<h5 class="anchored" data-anchor-id="applying-bic-for-selecting-the-best-model">Applying BIC for selecting the best model</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LC3 <span class="sc">~</span> MAP <span class="sc">+</span> MAT <span class="sc">+</span> JJAMAP <span class="sc">+</span> DJFMAP <span class="sc">+</span> LONG <span class="sc">+</span> LAT, <span class="at">data =</span> df)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co"># we apply k = log of the number of observations to represent BIC</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="co"># n is the number of observations in your dataset</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(df)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>model5_BIC <span class="ot">&lt;-</span> <span class="fu">step</span>(model5, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">k =</span> <span class="fu">log</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-186.47
LC3 ~ MAP + MAT + JJAMAP + DJFMAP + LONG + LAT

         Df Sum of Sq    RSS     AIC
- MAT     1   0.00030 3.7611 -190.76
- LONG    1   0.02714 3.7879 -190.24
- MAP     1   0.09065 3.8514 -189.02
- DJFMAP  1   0.10274 3.8635 -188.79
- JJAMAP  1   0.17554 3.9363 -187.43
&lt;none&gt;                3.7608 -186.47
- LAT     1   1.09047 4.8513 -172.18

Step:  AIC=-190.76
LC3 ~ MAP + JJAMAP + DJFMAP + LONG + LAT

         Df Sum of Sq    RSS     AIC
- LONG    1    0.0282 3.7893 -194.50
- MAP     1    0.0904 3.8515 -193.31
- DJFMAP  1    0.1030 3.8641 -193.08
- JJAMAP  1    0.1756 3.9367 -191.72
&lt;none&gt;                3.7611 -190.76
- LAT     1    3.5320 7.2931 -146.71

Step:  AIC=-194.5
LC3 ~ MAP + JJAMAP + DJFMAP + LAT

         Df Sum of Sq    RSS     AIC
- MAP     1    0.0643 3.8535 -197.56
- DJFMAP  1    0.0753 3.8646 -197.36
- JJAMAP  1    0.1682 3.9575 -195.62
&lt;none&gt;                3.7893 -194.50
- LAT     1    3.5512 7.3404 -150.52

Step:  AIC=-197.57
LC3 ~ JJAMAP + DJFMAP + LAT

         Df Sum of Sq    RSS     AIC
&lt;none&gt;                3.8535 -197.56
- DJFMAP  1    0.2393 4.0929 -197.46
- JJAMAP  1    0.2990 4.1526 -196.40
- LAT     1    3.6041 7.4577 -153.66</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># final model with the best BIC</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model5_BIC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LC3 ~ JJAMAP + DJFMAP + LAT, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.55475 -0.16509  0.02634  0.18400  0.48787 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -1.724723   0.305825  -5.640 3.46e-07 ***
JJAMAP      -1.001984   0.433027  -2.314   0.0237 *  
DJFMAP      -1.005341   0.485632  -2.070   0.0422 *  
LAT          0.042309   0.005267   8.033 1.74e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2363 on 69 degrees of freedom
Multiple R-squared:  0.5016,    Adjusted R-squared:  0.4799 
F-statistic: 23.15 on 3 and 69 DF,  p-value: 1.775e-10</code></pre>
</div>
</div>
<p>Final equation for the model 5 (BIC):</p>
<div class="cell">
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{LC3} = \beta_{0} + \beta_{1}(\operatorname{JJAMAP}) + \beta_{2}(\operatorname{DJFMAP}) + \beta_{3}(\operatorname{LAT}) + \epsilon
\]</span></p>
</div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{LC3}} = -1.72 - 1(\operatorname{JJAMAP}) - 1.01(\operatorname{DJFMAP}) + 0.04(\operatorname{LAT})
\]</span></p>
</div>
</div>
</section>
</section>
<section id="when-to-use-aic-or-bic" class="level4">
<h4 class="anchored" data-anchor-id="when-to-use-aic-or-bic">When to use AIC or BIC</h4>
<ul>
<li><p>Use <strong>AIC</strong> for better predictive accuracy, especially when working with smaller datasets or when the true model is likely complex.</p></li>
<li><p>Use <strong>BIC</strong> for simpler, more parsimonious models, especially when you have a large dataset and want to avoid overfitting.</p></li>
</ul>
</section>
<section id="importance-of-rmse" class="level4">
<h4 class="anchored" data-anchor-id="importance-of-rmse">Importance of RMSE</h4>
<p>The Root Mean Squared Error (RMSE) is a key metric for evaluating the performance of predictive models, especially in regression analysis. It provides a measure of how well a model’s predictions match the actual observed data. Here are some reasons why RMSE is important in evaluating models:</p>
<section id="measures-prediction-accuracy" class="level5">
<h5 class="anchored" data-anchor-id="measures-prediction-accuracy">1. <strong>Measures Prediction Accuracy</strong>:</h5>
<p>RMSE gives a direct indication of how close the predicted values are to the actual values in the dataset. Lower RMSE values indicate better fit, as they suggest that the predictions are closer to the real observations.</p>
</section>
<section id="interpretability" class="level5">
<h5 class="anchored" data-anchor-id="interpretability">2. <strong>Interpretability</strong>:</h5>
<p>RMSE is expressed in the same units as the dependent variable (response variable), making it easy to interpret in the context of the problem. For example, if you’re predicting house prices in dollars, RMSE will tell you the average prediction error in dollars, which makes it more intuitive.</p>
</section>
<section id="sensitive-to-large-errors" class="level5">
<h5 class="anchored" data-anchor-id="sensitive-to-large-errors">3. <strong>Sensitive to Large Errors</strong>:</h5>
<p>RMSE gives more weight to large errors due to the squaring of the residuals before averaging. This makes RMSE a good choice when you want to penalize models that make large prediction errors and want to emphasize minimizing significant deviations.</p>
</section>
<section id="comparison-of-models" class="level5">
<h5 class="anchored" data-anchor-id="comparison-of-models">4. <strong>Comparison of Models</strong>:</h5>
<p>RMSE is often used to compare different models’ performances. The model with the lowest RMSE is usually considered the better model when comparing across models with similar complexity and scale. It helps in choosing between competing models during model selection.</p>
</section>
<section id="standard-model-performance-metric" class="level5">
<h5 class="anchored" data-anchor-id="standard-model-performance-metric">5. <strong>Standard Model Performance Metric</strong>:</h5>
<p>RMSE is one of the most commonly used metrics in machine learning and statistical modeling. It provides a standard way to evaluate models across different domains and applications.</p>
</section>
<section id="limitations-of-rmse" class="level5">
<h5 class="anchored" data-anchor-id="limitations-of-rmse">Limitations of RMSE:</h5>
<ul>
<li><p><strong>Sensitive to Scale</strong>: If your dependent variable has a wide range, RMSE values can be misleading. In such cases, normalized error metrics like MAE (Mean Absolute Error) might complement RMSE.</p></li>
<li><p><strong>Doesn’t Work Well with Outliers</strong>: Since RMSE squares the errors, it can be disproportionately affected by outliers, making it essential to consider this when choosing it as a performance measure.</p></li>
</ul>
<p>In summary, RMSE is important because it gives a clear, interpretable, and meaningful measure of prediction accuracy and helps guide model comparison and selection based on how well a model can predict unseen data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(model5_BIC<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.229757</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>